plugins {
	id "java"
	id "application"
	id "idea"
}

project.version = "0.1"

repositories {
	mavenCentral()
}

dependencies {
	implementation libs.log4j
	implementation libs.gson
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

application {
	mainClass = "Main"

	applicationDefaultJvmArgs = [
		"-Dshattered.workspace.root=$rootDir/run"
	]
}

jar {
	manifest {
		attributes(
			"Enable-Native-Access": "ALL-UNNAMED",
			"Main-Class": "Main"
		)
	}
	archiveBaseName = "shattered"
}