java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

idea {
	module {
		downloadJavadoc = true
		downloadSources = true
	}
}

repositories {
	mavenCentral()
	maven { url = "https://central.sonatype.com/repository/maven-snapshots" }
}

tasks.withType(JavaCompile).configureEach {
	options.setIncremental(true)
}